/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/board_rect_end.glb -o public/modelComponent/Board_Rect.jsx -r public 
*/

import React from 'react'
import { useGLTF, Decal, useTexture } from '@react-three/drei'

export function Board_Rect({dUrl, dPos, dRot, dScale}) {
  const { nodes, materials } = useGLTF('/board_rect_end.glb');
  const texture = useTexture(dUrl || '/Quagsire.webp');
  
  let decal = null;
  if (dUrl) {
    decal = (
      <Decal
        debug
        position={dPos}
        rotation={dRot}
        scale={dScale}
      >
        <meshBasicMaterial
          map={texture}
          transparent
          opacity={0.5}
          polygonOffset
          polygonOffsetFactor={-1}
        />
      </Decal>
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} scale={[1, 1.008, 1]}>
        <meshBasicMaterial transparent={true} opacity={0} />
        {decal}
      </mesh>
    </group>
  )
}

useGLTF.preload('/board_rect_end.glb')
