/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/board-rect-planed.glb -o src/components/Board_Rect.jsx -r public 
*/

import React from 'react'
import { useGLTF, Decal, useTexture} from '@react-three/drei'

export function Board_Rect({dUrl, dPos, dRot, dScale}) {
  const { nodes, materials } = useGLTF('/board-rect-planed.glb');
  const texture = useTexture(dUrl || '/Quagsire.webp');

  let decal = null;
  if (dUrl) {
    decal = (
      <Decal
        debug
        position={dPos}
        rotation={dRot}
        scale={dScale}
        >
        <meshBasicMaterial
            map={texture}
            transparent
            polygonOffset
            polygonOffsetFactor={-1}
        />
      </Decal>
    )
  }

  return (
    <group dispose={null}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']}>
            {decal}
        </mesh>
    </group>
  )
}

useGLTF.preload('/board-rect.glb')
