/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bowl_end.glb -o public/modelComponent/Bowl.jsx -r public 
*/
import React from 'react'
import { useGLTF, Decal, useTexture } from '@react-three/drei'

export function Bowl({dUrl, dPos, dRot, dScale}) {
  const {nodes, materials} = useGLTF('/bowl_end.glb');
  const texture = useTexture(dUrl || '/Quagsire.webp');

  let decal = null;
  if (dUrl) {
    decal = (
      <Decal
        debug
        position={dPos}
        rotation={dRot}
        scale={dScale}
      >
        <meshBasicMaterial
          map={texture}
          transparent
          opacity={0.5}
          polygonOffset
          polygonOffsetFactor={-1}
        />
      </Decal>
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Sphere001.geometry} scale={1.008}>
        <meshBasicMaterial transparent={true} opacity={0} />
        {decal}
      </mesh>
    </group>
  )
}

useGLTF.preload('/bowl_end.glb')
