/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/round_cuttingboard_final.glb -o src/components/modelComponents/Board_Round.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import Design from '../design.jsx';

export function Board_Round({dUrl, dPos, dRot, dScale, imageArray, imageInfoArray, selectedDesign}) {
  const { nodes, materials } = useGLTF('/round_cuttingboard_final.glb')
  
  let placedDesigns = null;
  if (imageInfoArray.length > 0) {
    placedDesigns = imageInfoArray.map((info, i) => {

      if (!info || !imageArray[i] || i === selectedDesign) return null;

      return (
        <Design
            key={i}
            url={imageArray[i].filtered}
            pos={info.pos}
            rot={info.rot}
            scale={info.scale}
            opac={0.5}
        />
      )
    });
  }

  let curDesign = null;
  if (dUrl) {
    curDesign = (
        <Design
            url={imageArray[selectedDesign].filtered}
            pos={dPos}
            rot={dRot}
            scale={dScale}
            opac={0.3}
        />
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['DecoLoc.001']}>
        <meshBasicMaterial transparent={true} opacity={0} />
          {placedDesigns}
          {curDesign}
      </mesh>
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/round_cuttingboard_final.glb')
