/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/board_rect_end.glb -o public/modelComponent/Board_Rect.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import Design from '../design.jsx';

export function Board_Rect({dUrl, dPos, dRot, dScale, imageArray, imageInfoArray, selectedDesign}) {
  const { nodes, materials } = useGLTF('/board_rect_end.glb');
  
  let placedDesigns = null;
  if (imageInfoArray.length > 0) {
    placedDesigns = imageInfoArray.map((info, i) => {

      //To not render twice
      if (!info || !imageArray[i] || i === selectedDesign) return null;

      return (
        <Design
            key={i}
            url={imageArray[i].filtered}
            pos={info.pos}
            rot={info.rot}
            scale={info.scale}
            opac={1}
        />
      )
    });
  }

  let curDesign = null;
  if (dUrl) {
    curDesign = (
        <Design
            url={imageArray[selectedDesign].filtered}
            pos={dPos}
            rot={dRot}
            scale={dScale}
            opac={0.8}
        />
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} scale={[1, 1.008, 1]}>
        <meshBasicMaterial transparent={true} opacity={0} />
        {placedDesigns}
        {curDesign}
      </mesh>
    </group>
  )
}

useGLTF.preload('/board_rect_end.glb');


