/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bowl_end.glb -o public/modelComponent/Bowl.jsx -r public 
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'

import Design from '../design.jsx';

export function Bowl({dUrl, dPos, dRot, dScale, imageArray, imageInfoArray, selectedDesign}) {
  const {nodes, materials} = useGLTF('/bowl_end.glb');
  let placedDesigns = null;
  if (imageInfoArray.length > 0) {
    placedDesigns = imageInfoArray.map((info, i) => {

      //To not render twice
      if (!info || !imageArray[i] || i === selectedDesign) return null;

      return (
        <Design
            key={i}
            url={imageArray[i].filtered}
            pos={info.pos}
            rot={info.rot}
            scale={info.scale}
            opac={0.5}
        />
      )
    });
  }

  let curDesign = null;
  if (dUrl) {
    curDesign = (
        <Design
            url={imageArray[selectedDesign].filtered}
            pos={dPos}
            rot={dRot}
            scale={dScale}
            opac={0.3}
        />
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Sphere001.geometry} scale={1.008}>
        <meshBasicMaterial transparent={true} opacity={0} />
          {placedDesigns}
          {curDesign}
      </mesh>
    </group>
  )
}

useGLTF.preload('/bowl_end.glb')
