/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rect_cuttingboard.glb -o src/components/modelComponents/Board_Rect.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import Design from '../design.jsx';
import msqr from '../../utils/msqr.js';

export function Emblem({dUrl, dPos, dRot, dScale, imageArray, imageInfoArray, selectedDesign}) {
  const { nodes, materials } = useGLTF('/rect_cuttingboard.glb');
  
  let curDesign = null;
  if (dUrl) {
    curDesign = (
        <Design
            url={imageArray[selectedDesign].filtered}
            pos={dPos}
            rot={dRot}
            scale={dScale}
            opac={0.8}
        />
    )
  }

  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['DecoLoc.004']} scale={[1, 1.012, 1]}>
        <meshBasicMaterial transparent={true} opacity={0} />
        {placedDesigns}
        {curDesign}
      </mesh>
    </group>
  )
}
